CREATE OR REPLACE VIEW public.providers_v AS
SELECT b.id,
       b.pubkey,
       b.service,
       b.bond,
       b.metadata_uri,
       b.metadata_nonce,
       b.status,
       b.min_contract_duration,
       b.max_contract_duration,
       b.settlement_duration,
       b.created,
       b.updated,
       b.metadata_nonce_value,
       COALESCE(b.metadata_version, ''::text) AS metadata_version,
       b.metadata_moniker,
       b.metadata_website,
       b.metadata_description,
       b.metadata_location,
       b.metadata_free_rate_limit,
       COALESCE(b.metadata_free_rate_limit_duration, (0)::bigint) AS metadata_free_rate_limit_duration,
       COALESCE(b.subscription_rate, '0'::text) AS subscription_rate,
       COALESCE(b.paygo_rate, '0'::text) AS paygo_rate,
       b.contract_count,
       b.birth_height,
       b.cur_height,
       b.total_paid,
       (b.cur_height - (b.birth_height)::numeric) AS age
FROM providers_base_v b;