{
  "id": "github.com/arkeonetwork/arkeo",
  "swagger": "2.0",
  "info":
    {
      "description": "Chain github.com/arkeonetwork/arkeo REST API",
      "title": "HTTP API Console",
      "contact": { "name": "github.com/arkeonetwork/arkeo" },
    },
  "paths": {},
}
