before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=1

builds:
  - id: arkeod-linux-amd64
    binary: arkeod
    main: ./cmd/arkeod
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w
      - -X main.commit={{.Commit}}
      - -X main.date={{ .CommitDate }}
      - -X github.com/cosmos/cosmos-sdk/version.Name=Arkeo
      - -X github.com/cosmos/cosmos-sdk/version.AppName=arkeo
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags={{ .Env.BUILD_TAG }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/arkeonetwork/arkeo/x/arkeo/configs.Version=v{{ .Version }}
      - -X github.com/arkeonetwork/arkeo/x/arkeo/configs.GitCommit={{ .Commit }}
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs --static -lm'
    tags:
      - '{{ .Env.BUILD_TAG }}'

release:
  skip_upload: '{{ if eq .Env.RELEASE "true" }}false{{else}}true{{end}}'
archives:
  - id: w/version
    builds:
      - arkeod-linux-amd64
    name_template: '{{ .ProjectName }}d_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: false
    format: zip
    files:
      - none*
  - id: wo/version
    builds:
      - arkeod-linux-amd64
    name_template: '{{ .ProjectName }}d_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: false
    format: zip
    files:
      - none*
  - id: binary
    builds:
      - arkeod-linux-amd64
    name_template: '{{ .ProjectName }}d_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: false
    format: binary
    files:
      - none*
checksum:
  name_template: '{{ .ProjectName }}d_v{{ .Version }}_checksums.txt'
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - 'ghcr.io/arkeonetwork/{{ .ProjectName }}d:{{if eq .Env.RELEASE "true"}}v{{ .Version }}-amd64{{else}}{{ .ShortCommit }}-amd64{{end}}'
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}d"
      - "--label=org.opencontainers.image.description={{.ProjectName}}d"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version=v{{.Version}}"
      - "--label=org.opencontainers.image.url=https://arkeo.network/"
      - "--label=org.opencontainers.image.source=https://github.com/arkeonetwork/arkeo"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.dev
    image_templates:
      - 'ghcr.io/arkeonetwork/{{ .ProjectName }}d-dev:{{if eq .Env.RELEASE "true"}}v{{ .Version }}{{else}}{{ .ShortCommit }}{{end}}-amd64'
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}d"
      - "--label=org.opencontainers.image.description={{.ProjectName}}d"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version=v{{.Version}}"
      - "--label=org.opencontainers.image.url=https://arkeo.network/"
      - "--label=org.opencontainers.image.source=https://github.com/arkeonetwork/arkeo"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"