---
version: "3"

services:
  node:
    image: ghcr.io/arkeonetwork/arkeo-dev:${IMAGE_TAG}
    entrypoint:
      - /opt/genesis.sh
    build:
      dockerfile: ./Dockerfile
    ports:
      - 1317:1317
      - 26657:26657
      - 26656:26656
    volumes:
      - ./scripts:/opt:z
      - ".arkeo:/root/.arkeo:rw"
    environment:
      NET: "mocknet"
