version: "3"

services:
  node:
    image: ${IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile.localnet  # Ensure the Dockerfile is correctly referenced
    entrypoint:
      - bash
      - -c
      - |
        ./genesis.sh && \
        arkeod start
    ports:
      - 1317:1317
      - 26657:26657
      - 26656:26656
    volumes:
      - ./scripts:/scripts:z
    working_dir: /scripts
