// DONTCOVER
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: arkeo/arkeo/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ValidatorVersion defines the version of a validator in genesis state.
type ValidatorVersion struct {
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	Version          int64  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *ValidatorVersion) Reset()         { *m = ValidatorVersion{} }
func (m *ValidatorVersion) String() string { return proto.CompactTextString(m) }
func (*ValidatorVersion) ProtoMessage()    {}
func (*ValidatorVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_caae968dd754c6d4, []int{0}
}
func (m *ValidatorVersion) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorVersion.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorVersion.Merge(m, src)
}
func (m *ValidatorVersion) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorVersion.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorVersion proto.InternalMessageInfo

func (m *ValidatorVersion) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *ValidatorVersion) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

// GenesisState defines the arkeo module's genesis state.
type GenesisState struct {
	Params                 Params                  `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Providers              []Provider              `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers"`
	Contracts              []Contract              `protobuf:"bytes,3,rep,name=contracts,proto3" json:"contracts"`
	NextContractId         uint64                  `protobuf:"varint,4,opt,name=next_contract_id,json=nextContractId,proto3" json:"next_contract_id,omitempty"`
	ContractExpirationSets []ContractExpirationSet `protobuf:"bytes,5,rep,name=contract_expiration_sets,json=contractExpirationSets,proto3" json:"contract_expiration_sets"`
	UserContractSets       []UserContractSet       `protobuf:"bytes,6,rep,name=user_contract_sets,json=userContractSets,proto3" json:"user_contract_sets"`
	Version                int64                   `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	ValidatorVersions      []ValidatorVersion      `protobuf:"bytes,8,rep,name=validator_versions,json=validatorVersions,proto3" json:"validator_versions"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_caae968dd754c6d4, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetProviders() []Provider {
	if m != nil {
		return m.Providers
	}
	return nil
}

func (m *GenesisState) GetContracts() []Contract {
	if m != nil {
		return m.Contracts
	}
	return nil
}

func (m *GenesisState) GetNextContractId() uint64 {
	if m != nil {
		return m.NextContractId
	}
	return 0
}

func (m *GenesisState) GetContractExpirationSets() []ContractExpirationSet {
	if m != nil {
		return m.ContractExpirationSets
	}
	return nil
}

func (m *GenesisState) GetUserContractSets() []UserContractSet {
	if m != nil {
		return m.UserContractSets
	}
	return nil
}

func (m *GenesisState) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GenesisState) GetValidatorVersions() []ValidatorVersion {
	if m != nil {
		return m.ValidatorVersions
	}
	return nil
}

func init() {
	proto.RegisterType((*ValidatorVersion)(nil), "arkeo.arkeo.ValidatorVersion")
	proto.RegisterType((*GenesisState)(nil), "arkeo.arkeo.GenesisState")
}

func init() { proto.RegisterFile("arkeo/arkeo/genesis.proto", fileDescriptor_caae968dd754c6d4) }

var fileDescriptor_caae968dd754c6d4 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x6f, 0xd6, 0xd0, 0x31, 0x17, 0xa1, 0x60, 0xfe, 0xc8, 0x4c, 0x10, 0xa2, 0x9e, 0x22, 0x4d,
	0xca, 0xc4, 0x38, 0x71, 0x64, 0x68, 0x42, 0xdc, 0xa6, 0x4c, 0x4c, 0x82, 0x4b, 0xe4, 0x26, 0x4f,
	0xc1, 0x2a, 0x8b, 0x23, 0x3f, 0xb7, 0x94, 0x0f, 0xc0, 0x9d, 0x8f, 0xb5, 0xe3, 0x8e, 0x9c, 0x10,
	0x6a, 0xbf, 0x08, 0xaa, 0xed, 0x24, 0x0d, 0xca, 0xc5, 0x89, 0x7f, 0x7f, 0xde, 0xef, 0x59, 0xef,
	0x91, 0xe7, 0x5c, 0x2d, 0x40, 0x9e, 0xda, 0xb3, 0x84, 0x0a, 0x50, 0x60, 0x52, 0x2b, 0xa9, 0x25,
	0x9d, 0x1a, 0x30, 0x31, 0xe7, 0xf1, 0x93, 0x52, 0x96, 0xd2, 0xe0, 0xa7, 0xbb, 0x3f, 0x2b, 0x39,
	0x66, 0xfb, 0xee, 0x9a, 0x2b, 0x7e, 0x83, 0x43, 0xcc, 0x02, 0xa0, 0x06, 0x65, 0x99, 0xd9, 0x67,
	0x12, 0x5c, 0xf3, 0x6f, 0xa2, 0xe0, 0x5a, 0xaa, 0x6b, 0x50, 0x28, 0x64, 0x45, 0x4f, 0xc8, 0xa3,
	0x55, 0x83, 0x65, 0xbc, 0x28, 0x14, 0x20, 0x32, 0x2f, 0xf2, 0xe2, 0xa3, 0x34, 0x68, 0x89, 0x77,
	0x16, 0xa7, 0x8c, 0x1c, 0xae, 0xac, 0x8f, 0x1d, 0x44, 0x5e, 0x3c, 0x4e, 0x9b, 0xeb, 0xec, 0xa7,
	0x4f, 0x1e, 0x7c, 0xb0, 0x6f, 0xb8, 0xd2, 0x5c, 0x03, 0x7d, 0x4d, 0x26, 0xb6, 0x2b, 0x53, 0x6c,
	0x7a, 0xf6, 0x38, 0xd9, 0x7b, 0x53, 0x72, 0x69, 0xa8, 0x73, 0xff, 0xf6, 0xcf, 0xab, 0x51, 0xea,
	0x84, 0xf4, 0x2d, 0x39, 0xaa, 0x95, 0x5c, 0x89, 0x02, 0x14, 0xb2, 0x83, 0x68, 0x1c, 0x4f, 0xcf,
	0x9e, 0xf6, 0x5d, 0x8e, 0x75, 0xbe, 0x4e, 0xbd, 0xb3, 0xe6, 0xb2, 0xd2, 0x8a, 0xe7, 0x1a, 0xd9,
	0x78, 0xc0, 0xfa, 0xde, 0xb1, 0x8d, 0xb5, 0x55, 0xd3, 0x98, 0x04, 0x15, 0xac, 0x75, 0xd6, 0x20,
	0x99, 0x28, 0x98, 0x1f, 0x79, 0xb1, 0x9f, 0x3e, 0xdc, 0xe1, 0x8d, 0xf1, 0x63, 0x41, 0xe7, 0x84,
	0xb5, 0x22, 0x58, 0xd7, 0x42, 0x71, 0x2d, 0x64, 0x95, 0x21, 0x68, 0x64, 0xf7, 0x4c, 0xe6, 0x6c,
	0x30, 0xf3, 0xa2, 0xd5, 0x5e, 0x41, 0xd3, 0xc0, 0xb3, 0x7c, 0x88, 0x44, 0x7a, 0x49, 0xe8, 0x12,
	0x41, 0x75, 0xdd, 0x98, 0xea, 0x13, 0x53, 0xfd, 0x45, 0xaf, 0xfa, 0x27, 0x04, 0xd5, 0x24, 0x74,
	0x75, 0x83, 0x65, 0x1f, 0xee, 0xcd, 0xec, 0xb0, 0x37, 0x33, 0x9a, 0x12, 0xda, 0x8d, 0xde, 0x81,
	0xc8, 0xee, 0x9b, 0xac, 0x97, 0xbd, 0xac, 0xff, 0xb7, 0xc6, 0x85, 0x75, 0x9b, 0xe3, 0x70, 0x3c,
	0xbf, 0xb8, 0xdd, 0x84, 0xde, 0xdd, 0x26, 0xf4, 0xfe, 0x6e, 0x42, 0xef, 0xd7, 0x36, 0x1c, 0xdd,
	0x6d, 0xc3, 0xd1, 0xef, 0x6d, 0x38, 0xfa, 0x72, 0x52, 0x0a, 0xfd, 0x75, 0x39, 0x4f, 0x72, 0x79,
	0x63, 0x77, 0xb3, 0x02, 0xfd, 0x5d, 0xaa, 0x85, 0x5b, 0xd4, 0xb5, 0xfb, 0xea, 0x1f, 0x35, 0xe0,
	0x7c, 0x62, 0x16, 0xf6, 0xcd, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x26, 0x01, 0xbb, 0x24,
	0x03, 0x00, 0x00,
}

func (m *ValidatorVersion) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorVersion) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorVersion) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Version != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorVersions) > 0 {
		for iNdEx := len(m.ValidatorVersions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorVersions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.Version != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x38
	}
	if len(m.UserContractSets) > 0 {
		for iNdEx := len(m.UserContractSets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UserContractSets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.ContractExpirationSets) > 0 {
		for iNdEx := len(m.ContractExpirationSets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ContractExpirationSets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.NextContractId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextContractId))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Contracts) > 0 {
		for iNdEx := len(m.Contracts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Contracts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Providers) > 0 {
		for iNdEx := len(m.Providers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Providers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ValidatorVersion) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Version != 0 {
		n += 1 + sovGenesis(uint64(m.Version))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Providers) > 0 {
		for _, e := range m.Providers {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Contracts) > 0 {
		for _, e := range m.Contracts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.NextContractId != 0 {
		n += 1 + sovGenesis(uint64(m.NextContractId))
	}
	if len(m.ContractExpirationSets) > 0 {
		for _, e := range m.ContractExpirationSets {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.UserContractSets) > 0 {
		for _, e := range m.UserContractSets {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.Version != 0 {
		n += 1 + sovGenesis(uint64(m.Version))
	}
	if len(m.ValidatorVersions) > 0 {
		for _, e := range m.ValidatorVersions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ValidatorVersion) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorVersion: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorVersion: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Providers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Providers = append(m.Providers, Provider{})
			if err := m.Providers[len(m.Providers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contracts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contracts = append(m.Contracts, Contract{})
			if err := m.Contracts[len(m.Contracts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextContractId", wireType)
			}
			m.NextContractId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextContractId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractExpirationSets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractExpirationSets = append(m.ContractExpirationSets, ContractExpirationSet{})
			if err := m.ContractExpirationSets[len(m.ContractExpirationSets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserContractSets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserContractSets = append(m.UserContractSets, UserContractSet{})
			if err := m.UserContractSets[len(m.UserContractSets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorVersions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorVersions = append(m.ValidatorVersions, ValidatorVersion{})
			if err := m.ValidatorVersions[len(m.ValidatorVersions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
