// DONTCOVER
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: arkeo/arkeo/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	CommunityPoolPercentage   cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=community_pool_percentage,json=communityPoolPercentage,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"community_pool_percentage"`
	DevFundPercentage         cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=dev_fund_percentage,json=devFundPercentage,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"dev_fund_percentage"`
	GrantFundPercentage       cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=grant_fund_percentage,json=grantFundPercentage,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"grant_fund_percentage"`
	InflationChangePercentage cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=inflation_change_percentage,json=inflationChangePercentage,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"inflation_change_percentage"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c871f4fc73dfc5, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "arkeo.arkeo.Params")
}

func init() { proto.RegisterFile("arkeo/arkeo/params.proto", fileDescriptor_47c871f4fc73dfc5) }

var fileDescriptor_47c871f4fc73dfc5 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xbd, 0x4e, 0xf3, 0x30,
	0x14, 0x86, 0x93, 0xaf, 0x55, 0xa5, 0xcf, 0x4c, 0xb4, 0x20, 0xfa, 0x23, 0xb9, 0x88, 0x09, 0x09,
	0x91, 0xa8, 0x62, 0x63, 0x2c, 0x85, 0x89, 0xa1, 0x62, 0x64, 0x89, 0x1c, 0xe7, 0xd4, 0x8d, 0x5a,
	0xfb, 0x84, 0xc4, 0x29, 0xf4, 0x2e, 0x18, 0x19, 0xb9, 0x08, 0x26, 0xae, 0xa0, 0x63, 0xc5, 0x84,
	0x18, 0x2a, 0xd4, 0xde, 0x08, 0xc2, 0x8e, 0x4a, 0x05, 0x5b, 0x97, 0x93, 0xf8, 0xbc, 0xf6, 0xf3,
	0x2c, 0x2f, 0xa9, 0xb3, 0x74, 0x04, 0xe8, 0xdb, 0x99, 0xb0, 0x94, 0xc9, 0xcc, 0x4b, 0x52, 0xd4,
	0x58, 0xdd, 0x31, 0x3b, 0xcf, 0xcc, 0xe6, 0x9e, 0x40, 0x81, 0x66, 0xef, 0x7f, 0xff, 0xd9, 0x2b,
	0x4d, 0xca, 0x31, 0x93, 0x98, 0xf9, 0x21, 0xcb, 0xc0, 0x9f, 0x74, 0x42, 0xd0, 0xac, 0xe3, 0x73,
	0x8c, 0x55, 0x91, 0x37, 0x6c, 0x1e, 0xd8, 0x87, 0xf6, 0x60, 0xa3, 0xa3, 0xd7, 0x12, 0xa9, 0xf4,
	0x8d, 0xae, 0x2a, 0x49, 0x83, 0xa3, 0x94, 0xb9, 0x8a, 0xf5, 0x34, 0x48, 0x10, 0xc7, 0x41, 0x02,
	0x29, 0x07, 0xa5, 0x99, 0x80, 0xba, 0x7b, 0xe8, 0x1e, 0xff, 0xef, 0x76, 0x66, 0x8b, 0xb6, 0xf3,
	0xb1, 0x68, 0xb7, 0x2c, 0x23, 0x8b, 0x46, 0x5e, 0x8c, 0xbe, 0x64, 0x7a, 0xe8, 0x5d, 0x83, 0x60,
	0x7c, 0xda, 0x03, 0xfe, 0xf6, 0x72, 0x4a, 0x0a, 0x45, 0x0f, 0xf8, 0xcd, 0xc1, 0x9a, 0xd9, 0x47,
	0x1c, 0xf7, 0xd7, 0xc4, 0x2a, 0x23, 0xb5, 0x08, 0x26, 0xc1, 0x20, 0x57, 0xd1, 0xa6, 0xe8, 0xdf,
	0xb6, 0xa2, 0xdd, 0x08, 0x26, 0x57, 0xb9, 0x8a, 0x36, 0x14, 0x40, 0xf6, 0x45, 0xca, 0x94, 0xfe,
	0x23, 0x29, 0x6d, 0x2b, 0xa9, 0x19, 0xde, 0x2f, 0xcd, 0x1d, 0x69, 0xc5, 0x6a, 0x30, 0x66, 0x3a,
	0x46, 0x15, 0xf0, 0x21, 0x53, 0x02, 0x36, 0x65, 0xe5, 0x6d, 0x65, 0x8d, 0x35, 0xf5, 0xc2, 0x40,
	0x7f, 0x94, 0xe7, 0xe5, 0xa7, 0xe7, 0xb6, 0xd3, 0xbd, 0x9c, 0x2d, 0xa9, 0x3b, 0x5f, 0x52, 0xf7,
	0x73, 0x49, 0xdd, 0xc7, 0x15, 0x75, 0xe6, 0x2b, 0xea, 0xbc, 0xaf, 0xa8, 0x73, 0x7b, 0x22, 0x62,
	0x3d, 0xcc, 0x43, 0x8f, 0xa3, 0xb4, 0x9d, 0x52, 0xa0, 0xef, 0x31, 0x1d, 0x15, 0x05, 0x7b, 0x28,
	0xbe, 0x7a, 0x9a, 0x40, 0x16, 0x56, 0x4c, 0x15, 0xce, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x36,
	0xa2, 0x81, 0xbc, 0x84, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.InflationChangePercentage.Size()
		i -= size
		if _, err := m.InflationChangePercentage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.GrantFundPercentage.Size()
		i -= size
		if _, err := m.GrantFundPercentage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.DevFundPercentage.Size()
		i -= size
		if _, err := m.DevFundPercentage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.CommunityPoolPercentage.Size()
		i -= size
		if _, err := m.CommunityPoolPercentage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommunityPoolPercentage.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.DevFundPercentage.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.GrantFundPercentage.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.InflationChangePercentage.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommunityPoolPercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommunityPoolPercentage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DevFundPercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DevFundPercentage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GrantFundPercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GrantFundPercentage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InflationChangePercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InflationChangePercentage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
