FROM alpine:3.18

COPY ./arkeod /usr/bin/arkeod

WORKDIR /root/.arkeo

RUN apk add --no-cache bash jq

EXPOSE 1317

EXPOSE 26656

EXPOSE 26657

ENTRYPOINT [ "/bin/sh" ]

CMD [ "/usr/bin/arkeod" ,"help"]