FROM alpine:latest

COPY ./indexer /usr/bin/indexer

WORKDIR /root/.arkeo

RUN apk add --no-cache \
    bash \
    coreutils \
    jq \
    ca-certificates \
    curl

ENTRYPOINT [ "/bin/sh" ]

CMD [ "/usr/bin/indexer","help" ]