package common

import (
	"fmt"
	"strings"
)

type (
	Service  int32
	Services []Service
)

const (
	EmptyService Service = iota
	MockService  Service = 1
	BTCService   Service = 10
	ETHService   Service = 20
)

var ServiceLookup = map[string]int32{
	"unknown":                          0,
	"mock":                             1, // mock service for development purposes
	"arkeo-mainnet-fullnode":           2,
	"avax-mainnet-fullnode":            3,
	"avax-mainnet-archivenode":         4,
	"bch-mainnet-fullnode":             5,
	"bch-mainnet-lightnode":            6,
	"bnb-mainnet-fullnode":             7,
	"bsc-mainnet-fullnode":             8,
	"bsc-mainnet-archivenode":          9,
	"btc-mainnet-fullnode":             10,
	"btc-mainnet-lightnode":            11,
	"cardano-mainnet-relaynode":        12,
	"gaia-mainnet-rpc":                 13,
	"doge-mainnet-fullnode":            14,
	"doge-mainnet-lightnode":           15,
	"etc-mainnet-archivenode":          16,
	"etc-mainnet-fullnode":             17,
	"etc-mainnet-lightnode":            18,
	"eth-mainnet-archivenode":          19,
	"eth-mainnet-fullnode":             20,
	"eth-mainnet-lightnode":            21,
	"ltc-mainnet-fullnode":             22,
	"ltc-mainnet-lightnode":            23,
	"optimism-mainnet-fullnode":        24,
	"osmosis-mainnet-fullnode":         25,
	"polkadot-mainnet-fullnode":        26,
	"polkadot-mainnet-lightnode":       27,
	"polkadot-mainnet-archivenode":     28,
	"polygon-mainnet-fullnode":         29,
	"polygon-mainnet-archivenode":      30,
	"sol-mainnet-fullnode":             31,
	"thorchain-mainnet-fullnode":       32,
	"bch-mainnet-unchained":            33,
	"btc-mainnet-unchained":            34,
	"bnb-mainnet-unchained":            35,
	"bsc-mainnet-unchained":            36,
	"unknown-2":                        37,
	"gaia-mainnet-unchained":           38,
	"doge-mainnet-unchained":           39,
	"eth-mainnet-unchained":            40,
	"avax-mainnet-unchained":           41,
	"ltc-mainnet-unchained":            42,
	"osmosis-mainnet-unchained":        43,
	"thorchain-mainnet-unchained":      44,
	"optimism-mainnet-unchained":       45,
	"gaia-mainnet-grpc":                46,
	"btc-mainnet-blockbook":            47,
	"ltc-mainnet-blockbook":            48,
	"bch-mainnet-blockbook":            49,
	"doge-mainnet-blockbook":           50,
	"agoric-mainnet-archivenode":       51,
	"agoric-mainnet-fullnode":          52,
	"agoric-testnet-archivenode":       53,
	"agoric-testnet-fullnode":          54,
	"akash-mainnet-archivenode":        55,
	"akash-mainnet-fullnode":           56,
	"akash-testnet-archivenode":        57,
	"akash-testnet-fullnode":           58,
	"allora-mainnet-archivenode":       59,
	"allora-mainnet-fullnode":          60,
	"allora-testnet-archivenode":       61,
	"allora-testnet-fullnode":          62,
	"aptos-mainnet-fullnode":           63,
	"aptos-testnet-fullnode":           64,
	"arbitrum-mainnet-archivenode":     65,
	"arbitrum-mainnet-fullnode":        66,
	"arbitrum-mainnet-unchained":       67,
	"arbitrum-testnet-archivenode":     68,
	"arbitrum-testnet-fullnode":        69,
	"arch-mainnet-archivenode":         70,
	"arch-mainnet-fullnode":            71,
	"arch-testnet-archivenode":         72,
	"arch-testnet-fullnode":            73,
	"arkeo-mainnet-archivenode":        74,
	"arkeo-mainnet-unchained":          75,
	"arkeo-testnet-archivenode":        76,
	"arkeo-testnet-fullnode":           77,
	"arkeo-testnet-unchained":          78,
	"aur-mainnet-fullnode":             79,
	"avax-fuji-testnet-fullnode":       80,
	"avax-fuji-testnet-unchained":      81,
	"azero-mainnet-archivenode":        82,
	"azero-mainnet-fullnode":           83,
	"azero-testnet-archivenode":        84,
	"azero-testnet-fullnode":           85,
	"babylon-mainnet-fullnode":         86,
	"babylon-testnet-fullnode":         87,
	"base-mainnet-archivenode":         88,
	"base-mainnet-fullnode":            89,
	"base-mainnet-unchained":           90,
	"base-testnet-archivenode":         91,
	"base-testnet-fullnode":            92,
	"bch-testnet-blockbook":            93,
	"bch-testnet-fullnode":             94,
	"bch-testnet-lightnode":            95,
	"bch-testnet-unchained":            96,
	"bera-mainnet-archivenode":         97,
	"bera-mainnet-fullnode":            98,
	"bera-mainnet-unchained":           99,
	"bera-testnet-archivenode":         100,
	"bera-testnet-fullnode":            101,
	"blast-mainnet-archivenode":        102,
	"blast-mainnet-fullnode":           103,
	"blast-mainnet-unchained":          104,
	"blast-testnet-archivenode":        105,
	"blast-testnet-fullnode":           106,
	"bsc-testnet-archivenode":          107,
	"bsc-testnet-fullnode":             108,
	"btc-testnet-blockbook":            109,
	"btc-testnet-fullnode":             110,
	"btc-testnet-lightnode":            111,
	"btc-testnet-unchained":            112,
	"btg-mainnet-fullnode":             113,
	"ccd-mainnet-fullnode":             114,
	"celo-mainnet-archivenode":         115,
	"celo-mainnet-fullnode":            116,
	"celo-mainnet-unchained":           117,
	"celo-testnet-archivenode":         118,
	"celo-testnet-fullnode":            119,
	"cere-mainnet-fullnode":            120,
	"cfg-mainnet-archivenode":          121,
	"cfg-mainnet-fullnode":             122,
	"cheqd-mainnet-archivenode":        123,
	"cheqd-mainnet-fullnode":           124,
	"cro-mainnet-archivenode":          125,
	"cro-mainnet-fullnode":             126,
	"cro-testnet-archivenode":          127,
	"cro-testnet-fullnode":             128,
	"d-mainnet-fullnode":               129,
	"dash-mainnet-blockbook":           130,
	"dash-mainnet-fullnode":            131,
	"dcr-mainnet-fullnode":             132,
	"dfk-mainnet-archivenode":          133,
	"dfk-mainnet-fullnode":             134,
	"dfk-testnet-archivenode":          135,
	"dfk-testnet-fullnode":             136,
	"dgb-mainnet-fullnode":             137,
	"dvpn-mainnet-archivenode":         138,
	"dvpn-mainnet-fullnode":            139,
	"dym-mainnet-archivenode":          140,
	"dym-mainnet-fullnode":             141,
	"dym-mainnet-unchained":            142,
	"dym-testnet-archivenode":          143,
	"dym-testnet-fullnode":             144,
	"erowan-mainnet-archivenode":       145,
	"erowan-mainnet-fullnode":          146,
	"etc-mainnet-blockbook":            147,
	"etc-mainnet-unchained":            148,
	"eth-holesky-testnet-blockbook":    149,
	"eth-holesky-testnet-fullnode":     150,
	"eth-holesky-testnet-unchained":    151,
	"eth-mainnet-blockbook":            152,
	"eth-sepolia-testnet-blockbook":    153,
	"eth-sepolia-testnet-fullnode":     154,
	"eth-sepolia-testnet-unchained":    155,
	"evmos-mainnet-archivenode":        156,
	"evmos-mainnet-fullnode":           157,
	"evmos-testnet-archivenode":        158,
	"evmos-testnet-fullnode":           159,
	"fil-mainnet-fullnode":             160,
	"fil-mainnet-unchained":            161,
	"fil-testnet-fullnode":             162,
	"flare-mainnet-archivenode":        163,
	"flare-mainnet-fullnode":           164,
	"flare-mainnet-unchained":          165,
	"flare-testnet-archivenode":        166,
	"flare-testnet-fullnode":           167,
	"flo-mainnet-fullnode":             168,
	"flow-mainnet-fullnode":            169,
	"flow-mainnet-unchained":           170,
	"flow-testnet-fullnode":            171,
	"frx-mainnet-archivenode":          172,
	"frx-mainnet-fullnode":             173,
	"frx-mainnet-unchained":            174,
	"frx-testnet-archivenode":          175,
	"frx-testnet-fullnode":             176,
	"ftc-mainnet-fullnode":             177,
	"ftm-mainnet-archivenode":          178,
	"ftm-mainnet-fullnode":             179,
	"ftm-mainnet-unchained":            180,
	"ftm-testnet-archivenode":          181,
	"ftm-testnet-fullnode":             182,
	"fuse-mainnet-archivenode":         183,
	"fuse-mainnet-fullnode":            184,
	"fuse-testnet-archivenode":         185,
	"fuse-testnet-fullnode":            186,
	"gaia-mainnet-archivenode":         187,
	"gaia-mainnet-fullnode":            188,
	"gaia-mainnet-fullnode-grpc":       189,
	"gaia-testnet-archivenode":         190,
	"gaia-testnet-fullnode":            191,
	"glmr-mainnet-archivenode":         192,
	"glmr-mainnet-fullnode":            193,
	"glmr-mainnet-unchained":           194,
	"glmr-testnet-archivenode":         195,
	"glmr-testnet-fullnode":            196,
	"grs-mainnet-fullnode":             197,
	"hbar-mainnet-fullnode":            198,
	"hbar-mainnet-unchained":           199,
	"hbar-testnet-fullnode":            200,
	"hopr-mainnet-fullnode":            201,
	"hopr-testnet-fullnode":            202,
	"imx-mainnet-archivenode":          203,
	"imx-mainnet-fullnode":             204,
	"imx-mainnet-unchained":            205,
	"imx-testnet-archivenode":          206,
	"imx-testnet-fullnode":             207,
	"initia-mainnet-archivenode":       208,
	"initia-mainnet-fullnode":          209,
	"inj-mainnet-archivenode":          210,
	"inj-mainnet-fullnode":             211,
	"inj-mainnet-unchained":            212,
	"inj-testnet-archivenode":          213,
	"inj-testnet-fullnode":             214,
	"iota-mainnet-fullnode":            215,
	"iotx-mainnet-fullnode":            216,
	"ixo-mainnet-archivenode":          217,
	"ixo-mainnet-fullnode":             218,
	"jackal-mainnet-archivenode":       219,
	"jackal-mainnet-fullnode":          220,
	"juno-mainnet-archivenode":         221,
	"juno-mainnet-fullnode":            222,
	"juno-mainnet-unchained":           223,
	"juno-testnet-archivenode":         224,
	"juno-testnet-fullnode":            225,
	"kava-mainnet-archivenode":         226,
	"kava-mainnet-fullnode":            227,
	"kava-testnet-archivenode":         228,
	"kava-testnet-fullnode":            229,
	"klay-mainnet-archivenode":         230,
	"klay-mainnet-fullnode":            231,
	"klay-mainnet-unchained":           232,
	"klay-testnet-archivenode":         233,
	"klay-testnet-fullnode":            234,
	"koii-mainnet-fullnode":            235,
	"lbtc-mainnet-fullnode":            236,
	"linea-mainnet-archivenode":        237,
	"linea-mainnet-fullnode":           238,
	"linea-mainnet-unchained":          239,
	"linea-testnet-archivenode":        240,
	"linea-testnet-fullnode":           241,
	"ln-mainnet-fullnode":              242,
	"manta-mainnet-fullnode":           243,
	"manta-mainnet-unchained":          244,
	"mantle-mainnet-archivenode":       245,
	"mantle-mainnet-fullnode":          246,
	"mantle-mainnet-unchained":         247,
	"mantra-mainnet-archivenode":       248,
	"mantra-mainnet-fullnode":          249,
	"maya-mainnet-archivenode":         250,
	"maya-mainnet-fullnode":            251,
	"mina-mainnet-fullnode":            252,
	"mina-mainnet-unchained":           253,
	"mona-mainnet-fullnode":            254,
	"movr-mainnet-archivenode":         255,
	"movr-mainnet-fullnode":            256,
	"movr-testnet-archivenode":         257,
	"movr-testnet-fullnode":            258,
	"namada-mainnet-archivenode":       259,
	"namada-mainnet-fullnode":          260,
	"near-mainnet-fullnode":            261,
	"near-mainnet-unchained":           262,
	"near-testnet-fullnode":            263,
	"neutron-mainnet-archivenode":      264,
	"neutron-mainnet-fullnode":         265,
	"neutron-mainnet-unchained":        266,
	"ngm-mainnet-archivenode":          267,
	"ngm-mainnet-fullnode":             268,
	"ngm-testnet-archivenode":          269,
	"ngm-testnet-fullnode":             270,
	"nibiru-mainnet-archivenode":       271,
	"nibiru-mainnet-fullnode":          272,
	"nlg-mainnet-fullnode":             273,
	"nmc-mainnet-fullnode":             274,
	"nomic-mainnet-archivenode":        275,
	"nomic-mainnet-fullnode":           276,
	"one-mainnet-fullnode":             277,
	"one-testnet-fullnode":             278,
	"optimism-mainnet-archivenode":     279,
	"osmosis-mainnet-archivenode":      280,
	"paloma-mainnet-archivenode":       281,
	"paloma-mainnet-fullnode":          282,
	"part-mainnet-fullnode":            283,
	"penumbra-mainnet-archivenode":     284,
	"penumbra-mainnet-fullnode":        285,
	"polkadot-testnet-archivenode":     286,
	"polkadot-testnet-fullnode":        287,
	"polkadot-testnet-lightnode":       288,
	"polygon-Mumbai-testnet-fullnode":  289,
	"polygon-Mumbai-testnet-unchained": 290,
	"polygon-mainnet-unchained":        291,
	"ppc-mainnet-fullnode":             292,
	"pyth-mainnet-fullnode":            293,
	"pyth-testnet-fullnode":            294,
	"qtum-mainnet-blockbook":           295,
	"qtum-mainnet-fullnode":            296,
	"rdd-mainnet-fullnode":             297,
	"router-mainnet-archivenode":       298,
	"router-mainnet-fullnode":          299,
	"rvn-mainnet-blockbook":            300,
	"rvn-mainnet-fullnode":             301,
	"scroll-mainnet-archivenode":       302,
	"scroll-mainnet-fullnode":          303,
	"scroll-mainnet-unchained":         304,
	"scroll-testnet-archivenode":       305,
	"scroll-testnet-fullnode":          306,
	"scrt-mainnet-archivenode":         307,
	"scrt-mainnet-fullnode":            308,
	"seda-mainnet-fullnode":            309,
	"sei-mainnet-archivenode":          310,
	"sei-mainnet-fullnode":             311,
	"sei-mainnet-unchained":            312,
	"sei-testnet-archivenode":          313,
	"sei-testnet-fullnode":             314,
	"selfchain-mainnet-archivenode":    315,
	"selfchain-mainnet-fullnode":       316,
	"shardeum-mainnet-archivenode":     317,
	"shardeum-mainnet-fullnode":        318,
	"shardeum-mainnet-unchained":       319,
	"shardeum-testnet-archivenode":     320,
	"shardeum-testnet-fullnode":        321,
	"smart-mainnet-fullnode":           322,
	"sol-mainnet-unchained":            323,
	"sol-testnet-fullnode":             324,
	"somnia-mainnet-archivenode":       325,
	"somnia-mainnet-fullnode":          326,
	"starknet-mainnet-archivenode":     327,
	"starknet-mainnet-fullnode":        328,
	"starknet-testnet-archivenode":     329,
	"starknet-testnet-fullnode":        330,
	"stride-mainnet-archivenode":       331,
	"stride-mainnet-fullnode":          332,
	"sui-mainnet-fullnode":             333,
	"sui-testnet-fullnode":             334,
	"supra-mainnet-archivenode":        335,
	"supra-mainnet-fullnode":           336,
	"sys-mainnet-fullnode":             337,
	"taiko-mainnet-archivenode":        338,
	"taiko-mainnet-fullnode":           339,
	"taiko-mainnet-unchained":          340,
	"taiko-testnet-archivenode":        341,
	"taiko-testnet-fullnode":           342,
	"thorchain-mainnet-archivenode":    343,
	"tia-mainnet-archivenode":          344,
	"tia-mainnet-fullnode":             345,
	"tia-mainnet-unchained":            346,
	"tia-testnet-archivenode":          347,
	"tia-testnet-fullnode":             348,
	"ton-mainnet-fullnode":             349,
	"ton-testnet-fullnode":             350,
	"trx-mainnet-archivenode":          351,
	"trx-mainnet-fullnode":             352,
	"trx-mainnet-unchained":            353,
	"trx-testnet-archivenode":          354,
	"trx-testnet-fullnode":             355,
	"union-mainnet-archivenode":        356,
	"union-mainnet-fullnode":           357,
	"via-mainnet-fullnode":             358,
	"vtc-mainnet-fullnode":             359,
	"xdai-mainnet-archivenode":         360,
	"xdai-mainnet-fullnode":            361,
	"xdai-mainnet-unchained":           362,
	"xdai-testnet-archivenode":         363,
	"xdai-testnet-fullnode":            364,
	"xec-mainnet-fullnode":             365,
	"xlm-mainnet-fullnode":             366,
	"xlm-testnet-fullnode":             367,
	"xprt-mainnet-archivenode":         368,
	"xprt-mainnet-fullnode":            369,
	"zec-mainnet-blockbook":            370,
	"zec-mainnet-fullnode":             371,
	"zircuit-mainnet-archivenode":      372,
	"zircuit-mainnet-fullnode":         373,
	"zircuit-mainnet-unchained":        374,
	"zircuit-testnet-archivenode":      375,
	"zircuit-testnet-fullnode":         376,
	"zkfair-mainnet-archivenode":       377,
	"zkfair-mainnet-fullnode":          378,
	"zkfair-mainnet-unchained":         379,
	"zkfair-testnet-archivenode":       380,
	"zkfair-testnet-fullnode":          381,
	"zksync-mainnet-archivenode":       382,
	"zksync-mainnet-fullnode":          383,
	"zksync-mainnet-unchained":         384,
	"zksync-testnet-archivenode":       385,
	"zksync-testnet-fullnode":          386,
}

var ServiceReverseLookup = map[Service]string{
	0:   "unknown",
	1:   "mock",
	2:   "arkeo-mainnet-fullnode",
	3:   "avax-mainnet-fullnode",
	4:   "avax-mainnet-archivenode",
	5:   "bch-mainnet-fullnode",
	6:   "bch-mainnet-lightnode",
	7:   "bnb-mainnet-fullnode",
	8:   "bsc-mainnet-fullnode",
	9:   "bsc-mainnet-archivenode",
	10:  "btc-mainnet-fullnode",
	11:  "btc-mainnet-lightnode",
	12:  "cardano-mainnet-relaynode",
	13:  "gaia-mainnet-rpc",
	14:  "doge-mainnet-fullnode",
	15:  "doge-mainnet-lightnode",
	16:  "etc-mainnet-archivenode",
	17:  "etc-mainnet-fullnode",
	18:  "etc-mainnet-lightnode",
	19:  "eth-mainnet-archivenode",
	20:  "eth-mainnet-fullnode",
	21:  "eth-mainnet-lightnode",
	22:  "ltc-mainnet-fullnode",
	23:  "ltc-mainnet-lightnode",
	24:  "optimism-mainnet-fullnode",
	25:  "osmosis-mainnet-fullnode",
	26:  "polkadot-mainnet-fullnode",
	27:  "polkadot-mainnet-lightnode",
	28:  "polkadot-mainnet-archivenode",
	29:  "polygon-mainnet-fullnode",
	30:  "polygon-mainnet-archivenode",
	31:  "sol-mainnet-fullnode",
	32:  "thorchain-mainnet-fullnode",
	33:  "bch-mainnet-unchained",
	34:  "btc-mainnet-unchained",
	35:  "bnb-mainnet-unchained",
	36:  "bsc-mainnet-unchained",
	37:  "unknown-2",
	38:  "gaia-mainnet-unchained",
	39:  "doge-mainnet-unchained",
	40:  "eth-mainnet-unchained",
	41:  "avax-mainnet-unchained",
	42:  "ltc-mainnet-unchained",
	43:  "osmosis-mainnet-unchained",
	44:  "thorchain-mainnet-unchained",
	45:  "optimism-mainnet-unchained",
	46:  "gaia-mainnet-grpc",
	47:  "btc-mainnet-blockbook",
	48:  "ltc-mainnet-blockbook",
	49:  "bch-mainnet-blockbook",
	50:  "doge-mainnet-blockbook",
	51:  "agoric-mainnet-archivenode",
	52:  "agoric-mainnet-fullnode",
	53:  "agoric-testnet-archivenode",
	54:  "agoric-testnet-fullnode",
	55:  "akash-mainnet-archivenode",
	56:  "akash-mainnet-fullnode",
	57:  "akash-testnet-archivenode",
	58:  "akash-testnet-fullnode",
	59:  "allora-mainnet-archivenode",
	60:  "allora-mainnet-fullnode",
	61:  "allora-testnet-archivenode",
	62:  "allora-testnet-fullnode",
	63:  "aptos-mainnet-fullnode",
	64:  "aptos-testnet-fullnode",
	65:  "arbitrum-mainnet-archivenode",
	66:  "arbitrum-mainnet-fullnode",
	67:  "arbitrum-mainnet-unchained",
	68:  "arbitrum-testnet-archivenode",
	69:  "arbitrum-testnet-fullnode",
	70:  "arch-mainnet-archivenode",
	71:  "arch-mainnet-fullnode",
	72:  "arch-testnet-archivenode",
	73:  "arch-testnet-fullnode",
	74:  "arkeo-mainnet-archivenode",
	75:  "arkeo-mainnet-unchained",
	76:  "arkeo-testnet-archivenode",
	77:  "arkeo-testnet-fullnode",
	78:  "arkeo-testnet-unchained",
	79:  "aur-mainnet-fullnode",
	80:  "avax-fuji-testnet-fullnode",
	81:  "avax-fuji-testnet-unchained",
	82:  "azero-mainnet-archivenode",
	83:  "azero-mainnet-fullnode",
	84:  "azero-testnet-archivenode",
	85:  "azero-testnet-fullnode",
	86:  "babylon-mainnet-fullnode",
	87:  "babylon-testnet-fullnode",
	88:  "base-mainnet-archivenode",
	89:  "base-mainnet-fullnode",
	90:  "base-mainnet-unchained",
	91:  "base-testnet-archivenode",
	92:  "base-testnet-fullnode",
	93:  "bch-testnet-blockbook",
	94:  "bch-testnet-fullnode",
	95:  "bch-testnet-lightnode",
	96:  "bch-testnet-unchained",
	97:  "bera-mainnet-archivenode",
	98:  "bera-mainnet-fullnode",
	99:  "bera-mainnet-unchained",
	100: "bera-testnet-archivenode",
	101: "bera-testnet-fullnode",
	102: "blast-mainnet-archivenode",
	103: "blast-mainnet-fullnode",
	104: "blast-mainnet-unchained",
	105: "blast-testnet-archivenode",
	106: "blast-testnet-fullnode",
	107: "bsc-testnet-archivenode",
	108: "bsc-testnet-fullnode",
	109: "btc-testnet-blockbook",
	110: "btc-testnet-fullnode",
	111: "btc-testnet-lightnode",
	112: "btc-testnet-unchained",
	113: "btg-mainnet-fullnode",
	114: "ccd-mainnet-fullnode",
	115: "celo-mainnet-archivenode",
	116: "celo-mainnet-fullnode",
	117: "celo-mainnet-unchained",
	118: "celo-testnet-archivenode",
	119: "celo-testnet-fullnode",
	120: "cere-mainnet-fullnode",
	121: "cfg-mainnet-archivenode",
	122: "cfg-mainnet-fullnode",
	123: "cheqd-mainnet-archivenode",
	124: "cheqd-mainnet-fullnode",
	125: "cro-mainnet-archivenode",
	126: "cro-mainnet-fullnode",
	127: "cro-testnet-archivenode",
	128: "cro-testnet-fullnode",
	129: "d-mainnet-fullnode",
	130: "dash-mainnet-blockbook",
	131: "dash-mainnet-fullnode",
	132: "dcr-mainnet-fullnode",
	133: "dfk-mainnet-archivenode",
	134: "dfk-mainnet-fullnode",
	135: "dfk-testnet-archivenode",
	136: "dfk-testnet-fullnode",
	137: "dgb-mainnet-fullnode",
	138: "dvpn-mainnet-archivenode",
	139: "dvpn-mainnet-fullnode",
	140: "dym-mainnet-archivenode",
	141: "dym-mainnet-fullnode",
	142: "dym-mainnet-unchained",
	143: "dym-testnet-archivenode",
	144: "dym-testnet-fullnode",
	145: "erowan-mainnet-archivenode",
	146: "erowan-mainnet-fullnode",
	147: "etc-mainnet-blockbook",
	148: "etc-mainnet-unchained",
	149: "eth-holesky-testnet-blockbook",
	150: "eth-holesky-testnet-fullnode",
	151: "eth-holesky-testnet-unchained",
	152: "eth-mainnet-blockbook",
	153: "eth-sepolia-testnet-blockbook",
	154: "eth-sepolia-testnet-fullnode",
	155: "eth-sepolia-testnet-unchained",
	156: "evmos-mainnet-archivenode",
	157: "evmos-mainnet-fullnode",
	158: "evmos-testnet-archivenode",
	159: "evmos-testnet-fullnode",
	160: "fil-mainnet-fullnode",
	161: "fil-mainnet-unchained",
	162: "fil-testnet-fullnode",
	163: "flare-mainnet-archivenode",
	164: "flare-mainnet-fullnode",
	165: "flare-mainnet-unchained",
	166: "flare-testnet-archivenode",
	167: "flare-testnet-fullnode",
	168: "flo-mainnet-fullnode",
	169: "flow-mainnet-fullnode",
	170: "flow-mainnet-unchained",
	171: "flow-testnet-fullnode",
	172: "frx-mainnet-archivenode",
	173: "frx-mainnet-fullnode",
	174: "frx-mainnet-unchained",
	175: "frx-testnet-archivenode",
	176: "frx-testnet-fullnode",
	177: "ftc-mainnet-fullnode",
	178: "ftm-mainnet-archivenode",
	179: "ftm-mainnet-fullnode",
	180: "ftm-mainnet-unchained",
	181: "ftm-testnet-archivenode",
	182: "ftm-testnet-fullnode",
	183: "fuse-mainnet-archivenode",
	184: "fuse-mainnet-fullnode",
	185: "fuse-testnet-archivenode",
	186: "fuse-testnet-fullnode",
	187: "gaia-mainnet-archivenode",
	188: "gaia-mainnet-fullnode",
	189: "gaia-mainnet-fullnode-grpc",
	190: "gaia-testnet-archivenode",
	191: "gaia-testnet-fullnode",
	192: "glmr-mainnet-archivenode",
	193: "glmr-mainnet-fullnode",
	194: "glmr-mainnet-unchained",
	195: "glmr-testnet-archivenode",
	196: "glmr-testnet-fullnode",
	197: "grs-mainnet-fullnode",
	198: "hbar-mainnet-fullnode",
	199: "hbar-mainnet-unchained",
	200: "hbar-testnet-fullnode",
	201: "hopr-mainnet-fullnode",
	202: "hopr-testnet-fullnode",
	203: "imx-mainnet-archivenode",
	204: "imx-mainnet-fullnode",
	205: "imx-mainnet-unchained",
	206: "imx-testnet-archivenode",
	207: "imx-testnet-fullnode",
	208: "initia-mainnet-archivenode",
	209: "initia-mainnet-fullnode",
	210: "inj-mainnet-archivenode",
	211: "inj-mainnet-fullnode",
	212: "inj-mainnet-unchained",
	213: "inj-testnet-archivenode",
	214: "inj-testnet-fullnode",
	215: "iota-mainnet-fullnode",
	216: "iotx-mainnet-fullnode",
	217: "ixo-mainnet-archivenode",
	218: "ixo-mainnet-fullnode",
	219: "jackal-mainnet-archivenode",
	220: "jackal-mainnet-fullnode",
	221: "juno-mainnet-archivenode",
	222: "juno-mainnet-fullnode",
	223: "juno-mainnet-unchained",
	224: "juno-testnet-archivenode",
	225: "juno-testnet-fullnode",
	226: "kava-mainnet-archivenode",
	227: "kava-mainnet-fullnode",
	228: "kava-testnet-archivenode",
	229: "kava-testnet-fullnode",
	230: "klay-mainnet-archivenode",
	231: "klay-mainnet-fullnode",
	232: "klay-mainnet-unchained",
	233: "klay-testnet-archivenode",
	234: "klay-testnet-fullnode",
	235: "koii-mainnet-fullnode",
	236: "lbtc-mainnet-fullnode",
	237: "linea-mainnet-archivenode",
	238: "linea-mainnet-fullnode",
	239: "linea-mainnet-unchained",
	240: "linea-testnet-archivenode",
	241: "linea-testnet-fullnode",
	242: "ln-mainnet-fullnode",
	243: "manta-mainnet-fullnode",
	244: "manta-mainnet-unchained",
	245: "mantle-mainnet-archivenode",
	246: "mantle-mainnet-fullnode",
	247: "mantle-mainnet-unchained",
	248: "mantra-mainnet-archivenode",
	249: "mantra-mainnet-fullnode",
	250: "maya-mainnet-archivenode",
	251: "maya-mainnet-fullnode",
	252: "mina-mainnet-fullnode",
	253: "mina-mainnet-unchained",
	254: "mona-mainnet-fullnode",
	255: "movr-mainnet-archivenode",
	256: "movr-mainnet-fullnode",
	257: "movr-testnet-archivenode",
	258: "movr-testnet-fullnode",
	259: "namada-mainnet-archivenode",
	260: "namada-mainnet-fullnode",
	261: "near-mainnet-fullnode",
	262: "near-mainnet-unchained",
	263: "near-testnet-fullnode",
	264: "neutron-mainnet-archivenode",
	265: "neutron-mainnet-fullnode",
	266: "neutron-mainnet-unchained",
	267: "ngm-mainnet-archivenode",
	268: "ngm-mainnet-fullnode",
	269: "ngm-testnet-archivenode",
	270: "ngm-testnet-fullnode",
	271: "nibiru-mainnet-archivenode",
	272: "nibiru-mainnet-fullnode",
	273: "nlg-mainnet-fullnode",
	274: "nmc-mainnet-fullnode",
	275: "nomic-mainnet-archivenode",
	276: "nomic-mainnet-fullnode",
	277: "one-mainnet-fullnode",
	278: "one-testnet-fullnode",
	279: "optimism-mainnet-archivenode",
	280: "osmosis-mainnet-archivenode",
	281: "paloma-mainnet-archivenode",
	282: "paloma-mainnet-fullnode",
	283: "part-mainnet-fullnode",
	284: "penumbra-mainnet-archivenode",
	285: "penumbra-mainnet-fullnode",
	286: "polkadot-testnet-archivenode",
	287: "polkadot-testnet-fullnode",
	288: "polkadot-testnet-lightnode",
	289: "polygon-Mumbai-testnet-fullnode",
	290: "polygon-Mumbai-testnet-unchained",
	291: "polygon-mainnet-unchained",
	292: "ppc-mainnet-fullnode",
	293: "pyth-mainnet-fullnode",
	294: "pyth-testnet-fullnode",
	295: "qtum-mainnet-blockbook",
	296: "qtum-mainnet-fullnode",
	297: "rdd-mainnet-fullnode",
	298: "router-mainnet-archivenode",
	299: "router-mainnet-fullnode",
	300: "rvn-mainnet-blockbook",
	301: "rvn-mainnet-fullnode",
	302: "scroll-mainnet-archivenode",
	303: "scroll-mainnet-fullnode",
	304: "scroll-mainnet-unchained",
	305: "scroll-testnet-archivenode",
	306: "scroll-testnet-fullnode",
	307: "scrt-mainnet-archivenode",
	308: "scrt-mainnet-fullnode",
	309: "seda-mainnet-fullnode",
	310: "sei-mainnet-archivenode",
	311: "sei-mainnet-fullnode",
	312: "sei-mainnet-unchained",
	313: "sei-testnet-archivenode",
	314: "sei-testnet-fullnode",
	315: "selfchain-mainnet-archivenode",
	316: "selfchain-mainnet-fullnode",
	317: "shardeum-mainnet-archivenode",
	318: "shardeum-mainnet-fullnode",
	319: "shardeum-mainnet-unchained",
	320: "shardeum-testnet-archivenode",
	321: "shardeum-testnet-fullnode",
	322: "smart-mainnet-fullnode",
	323: "sol-mainnet-unchained",
	324: "sol-testnet-fullnode",
	325: "somnia-mainnet-archivenode",
	326: "somnia-mainnet-fullnode",
	327: "starknet-mainnet-archivenode",
	328: "starknet-mainnet-fullnode",
	329: "starknet-testnet-archivenode",
	330: "starknet-testnet-fullnode",
	331: "stride-mainnet-archivenode",
	332: "stride-mainnet-fullnode",
	333: "sui-mainnet-fullnode",
	334: "sui-testnet-fullnode",
	335: "supra-mainnet-archivenode",
	336: "supra-mainnet-fullnode",
	337: "sys-mainnet-fullnode",
	338: "taiko-mainnet-archivenode",
	339: "taiko-mainnet-fullnode",
	340: "taiko-mainnet-unchained",
	341: "taiko-testnet-archivenode",
	342: "taiko-testnet-fullnode",
	343: "thorchain-mainnet-archivenode",
	344: "tia-mainnet-archivenode",
	345: "tia-mainnet-fullnode",
	346: "tia-mainnet-unchained",
	347: "tia-testnet-archivenode",
	348: "tia-testnet-fullnode",
	349: "ton-mainnet-fullnode",
	350: "ton-testnet-fullnode",
	351: "trx-mainnet-archivenode",
	352: "trx-mainnet-fullnode",
	353: "trx-mainnet-unchained",
	354: "trx-testnet-archivenode",
	355: "trx-testnet-fullnode",
	356: "union-mainnet-archivenode",
	357: "union-mainnet-fullnode",
	358: "via-mainnet-fullnode",
	359: "vtc-mainnet-fullnode",
	360: "xdai-mainnet-archivenode",
	361: "xdai-mainnet-fullnode",
	362: "xdai-mainnet-unchained",
	363: "xdai-testnet-archivenode",
	364: "xdai-testnet-fullnode",
	365: "xec-mainnet-fullnode",
	366: "xlm-mainnet-fullnode",
	367: "xlm-testnet-fullnode",
	368: "xprt-mainnet-archivenode",
	369: "xprt-mainnet-fullnode",
	370: "zec-mainnet-blockbook",
	371: "zec-mainnet-fullnode",
	372: "zircuit-mainnet-archivenode",
	373: "zircuit-mainnet-fullnode",
	374: "zircuit-mainnet-unchained",
	375: "zircuit-testnet-archivenode",
	376: "zircuit-testnet-fullnode",
	377: "zkfair-mainnet-archivenode",
	378: "zkfair-mainnet-fullnode",
	379: "zkfair-mainnet-unchained",
	380: "zkfair-testnet-archivenode",
	381: "zkfair-testnet-fullnode",
	382: "zksync-mainnet-archivenode",
	383: "zksync-mainnet-fullnode",
	384: "zksync-mainnet-unchained",
	385: "zksync-testnet-archivenode",
	386: "zksync-testnet-fullnode",
}

var ServiceDescriptionMap = map[string]string{
	"unknown":                          "Unknown",
	"mock":                             "Mock",
	"arkeo-mainnet-fullnode":           "Arkeo Mainnet Fullnode",
	"avax-mainnet-fullnode":            "Avalanche Mainnet Fullnode",
	"avax-mainnet-archivenode":         "Avalanche Mainnet Archivenode",
	"bch-mainnet-fullnode":             "Bitcoin Cash Mainnet Fullnode",
	"bch-mainnet-lightnode":            "Bitcoin Cash Mainnet Lightnode",
	"bnb-mainnet-fullnode":             "BNB Beacon Chain Mainnet Fullnode",
	"bsc-mainnet-fullnode":             "Binance Smart Chain Mainnet Fullnode",
	"bsc-mainnet-archivenode":          "Binance Smart Chain Mainnet Archivenode",
	"btc-mainnet-fullnode":             "Bitcoin Mainnet Fullnode",
	"btc-mainnet-lightnode":            "Bitcoin Mainnet Lightnode",
	"cardano-mainnet-relaynode":        "Cardano Mainnet Relaynode",
	"gaia-mainnet-rpc":                 "Gaia Mainnet RPC",
	"doge-mainnet-fullnode":            "Dogecoin Mainnet Fullnode",
	"doge-mainnet-lightnode":           "Dogecoin Mainnet Lightnode",
	"etc-mainnet-archivenode":          "Ethereum Classic Mainnet Archivenode",
	"etc-mainnet-fullnode":             "Ethereum Classic Mainnet Fullnode",
	"etc-mainnet-lightnode":            "Ethereum Classic Mainnet Lightnode",
	"eth-mainnet-archivenode":          "Ethereum Mainnet Archivenode",
	"eth-mainnet-fullnode":             "Ethereum Mainnet Fullnode",
	"eth-mainnet-lightnode":            "Ethereum Mainnet Lightnode",
	"ltc-mainnet-fullnode":             "Litecoin Mainnet Fullnode",
	"ltc-mainnet-lightnode":            "Litecoin Mainnet Lightnode",
	"optimism-mainnet-fullnode":        "Optimism Mainnet Fullnode",
	"osmosis-mainnet-fullnode":         "Osmosis Mainnet Fullnode",
	"polkadot-mainnet-fullnode":        "Polkadot Mainnet Fullnode",
	"polkadot-mainnet-lightnode":       "Polkadot Mainnet Lightnode",
	"polkadot-mainnet-archivenode":     "Polkadot Mainnet Archivenode",
	"polygon-mainnet-fullnode":         "Polygon Mainnet Fullnode",
	"polygon-mainnet-archivenode":      "Polygon Mainnet Archivenode",
	"sol-mainnet-fullnode":             "Solana Mainnet Fullnode",
	"thorchain-mainnet-fullnode":       "THORChain Mainnet Fullnode",
	"bch-mainnet-unchained":            "Bitcoin Cash Mainnet Unchained",
	"btc-mainnet-unchained":            "Bitcoin Mainnet Unchained",
	"bnb-mainnet-unchained":            "BNB Beacon Chain Mainnet Unchained",
	"bsc-mainnet-unchained":            "Binance Smart Chain Mainnet Unchained",
	"unknown-2":                        "Unknown",
	"gaia-mainnet-unchained":           "Gaia Mainnet Unchained",
	"doge-mainnet-unchained":           "Dogecoin Mainnet Unchained",
	"eth-mainnet-unchained":            "Ethereum Mainnet Unchained",
	"avax-mainnet-unchained":           "Avalanche Mainnet Unchained",
	"ltc-mainnet-unchained":            "Litecoin Mainnet Unchained",
	"osmosis-mainnet-unchained":        "Osmosis Mainnet Unchained",
	"thorchain-mainnet-unchained":      "THORChain Mainnet Unchained",
	"optimism-mainnet-unchained":       "Optimism Mainnet Unchained",
	"gaia-mainnet-grpc":                "Gaia Mainnet GRPC",
	"btc-mainnet-blockbook":            "Bitcoin Mainnet Blockbook",
	"ltc-mainnet-blockbook":            "Litecoin Mainnet Blockbook",
	"bch-mainnet-blockbook":            "Bitcoin Cash Mainnet Blockbook",
	"doge-mainnet-blockbook":           "Dogecoin Mainnet Blockbook",
	"agoric-mainnet-archivenode":       "Agoric Mainnet Archivenode",
	"agoric-mainnet-fullnode":          "Agoric Mainnet Fullnode",
	"agoric-testnet-archivenode":       "Agoric Testnet Archivenode",
	"agoric-testnet-fullnode":          "Agoric Testnet Fullnode",
	"akash-mainnet-archivenode":        "Akash Mainnet Archivenode",
	"akash-mainnet-fullnode":           "Akash Mainnet Fullnode",
	"akash-testnet-archivenode":        "Akash Testnet Archivenode",
	"akash-testnet-fullnode":           "Akash Testnet Fullnode",
	"allora-mainnet-archivenode":       "Allora Mainnet Archivenode",
	"allora-mainnet-fullnode":          "Allora Mainnet Fullnode",
	"allora-testnet-archivenode":       "Allora Testnet Archivenode",
	"allora-testnet-fullnode":          "Allora Testnet Fullnode",
	"aptos-mainnet-fullnode":           "Aptos Mainnet Fullnode",
	"aptos-testnet-fullnode":           "Aptos Testnet Fullnode",
	"arbitrum-mainnet-archivenode":     "Arbitrum Mainnet Archivenode",
	"arbitrum-mainnet-fullnode":        "Arbitrum Mainnet Fullnode",
	"arbitrum-mainnet-unchained":       "Arbitrum Mainnet Unchained",
	"arbitrum-testnet-archivenode":     "Arbitrum Testnet Archivenode",
	"arbitrum-testnet-fullnode":        "Arbitrum Testnet Fullnode",
	"arch-mainnet-archivenode":         "Archway Mainnet Archivenode",
	"arch-mainnet-fullnode":            "Archway Mainnet Fullnode",
	"arch-testnet-archivenode":         "Archway Testnet Archivenode",
	"arch-testnet-fullnode":            "Archway Testnet Fullnode",
	"arkeo-mainnet-archivenode":        "Arkeo Mainnet Archivenode",
	"arkeo-mainnet-unchained":          "Arkeo Mainnet Unchained",
	"arkeo-testnet-archivenode":        "Arkeo Testnet Archivenode",
	"arkeo-testnet-fullnode":           "Arkeo Testnet Fullnode",
	"arkeo-testnet-unchained":          "Arkeo Testnet Unchained",
	"aur-mainnet-fullnode":             "Auroracoin Mainnet Fullnode",
	"avax-fuji-testnet-fullnode":       "Avalanche (C-Chain) Fuji Testnet Fullnode",
	"avax-fuji-testnet-unchained":      "Avalanche (C-Chain) Fuji Testnet Unchained",
	"azero-mainnet-archivenode":        "AlephZero Mainnet Archivenode",
	"azero-mainnet-fullnode":           "AlephZero Mainnet Fullnode",
	"azero-testnet-archivenode":        "AlephZero Testnet Archivenode",
	"azero-testnet-fullnode":           "AlephZero Testnet Fullnode",
	"babylon-mainnet-fullnode":         "Babylon EVM Mainnet Fullnode",
	"babylon-testnet-fullnode":         "Babylon EVM Testnet Fullnode",
	"base-mainnet-archivenode":         "Base Mainnet Archivenode",
	"base-mainnet-fullnode":            "Base Mainnet Fullnode",
	"base-mainnet-unchained":           "Base Mainnet Unchained",
	"base-testnet-archivenode":         "Base Testnet Archivenode",
	"base-testnet-fullnode":            "Base Testnet Fullnode",
	"bch-testnet-blockbook":            "Bitcoin Cash Testnet Blockbook",
	"bch-testnet-fullnode":             "Bitcoin Cash Testnet Fullnode",
	"bch-testnet-lightnode":            "Bitcoin Cash Testnet Lightnode",
	"bch-testnet-unchained":            "Bitcoin Cash Testnet Unchained",
	"bera-mainnet-archivenode":         "Berachain Mainnet Archivenode",
	"bera-mainnet-fullnode":            "Berachain Mainnet Fullnode",
	"bera-mainnet-unchained":           "Berachain Mainnet Unchained",
	"bera-testnet-archivenode":         "Berachain Testnet Archivenode",
	"bera-testnet-fullnode":            "Berachain Testnet Fullnode",
	"blast-mainnet-archivenode":        "Blast Mainnet Archivenode",
	"blast-mainnet-fullnode":           "Blast Mainnet Fullnode",
	"blast-mainnet-unchained":          "Blast Mainnet Unchained",
	"blast-testnet-archivenode":        "Blast Testnet Archivenode",
	"blast-testnet-fullnode":           "Blast Testnet Fullnode",
	"bsc-testnet-archivenode":          "Binance Smart Chain Testnet Archivenode",
	"bsc-testnet-fullnode":             "Binance Smart Chain Testnet Fullnode",
	"btc-testnet-blockbook":            "Bitcoin Testnet Blockbook",
	"btc-testnet-fullnode":             "Bitcoin Testnet Fullnode",
	"btc-testnet-lightnode":            "Bitcoin Testnet Lightnode",
	"btc-testnet-unchained":            "Bitcoin Testnet Unchained",
	"btg-mainnet-fullnode":             "Bitcoin Gold Mainnet Fullnode",
	"ccd-mainnet-fullnode":             "Concordium Mainnet Fullnode",
	"celo-mainnet-archivenode":         "Celo Mainnet Archivenode",
	"celo-mainnet-fullnode":            "Celo Mainnet Fullnode",
	"celo-mainnet-unchained":           "Celo Mainnet Unchained",
	"celo-testnet-archivenode":         "Celo Testnet Archivenode",
	"celo-testnet-fullnode":            "Celo Testnet Fullnode",
	"cere-mainnet-fullnode":            "Cere Mainnet Fullnode",
	"cfg-mainnet-archivenode":          "Centrifuge Mainnet Archivenode",
	"cfg-mainnet-fullnode":             "Centrifuge Mainnet Fullnode",
	"cheqd-mainnet-archivenode":        "Cheqd Mainnet Archivenode",
	"cheqd-mainnet-fullnode":           "Cheqd Mainnet Fullnode",
	"cro-mainnet-archivenode":          "Cronos Mainnet Archivenode",
	"cro-mainnet-fullnode":             "Cronos Mainnet Fullnode",
	"cro-testnet-archivenode":          "Cronos Testnet Archivenode",
	"cro-testnet-fullnode":             "Cronos Testnet Fullnode",
	"d-mainnet-fullnode":               "Denarius Mainnet Fullnode",
	"dash-mainnet-blockbook":           "Dash Mainnet Blockbook",
	"dash-mainnet-fullnode":            "Dash Mainnet Fullnode",
	"dcr-mainnet-fullnode":             "Decred Mainnet Fullnode",
	"dfk-mainnet-archivenode":          "DFK Mainnet Archivenode",
	"dfk-mainnet-fullnode":             "DFK Mainnet Fullnode",
	"dfk-testnet-archivenode":          "DFK Testnet Archivenode",
	"dfk-testnet-fullnode":             "DFK Testnet Fullnode",
	"dgb-mainnet-fullnode":             "DigiByte Mainnet Fullnode",
	"dvpn-mainnet-archivenode":         "Sentinel Mainnet Archivenode",
	"dvpn-mainnet-fullnode":            "Sentinel Mainnet Fullnode",
	"dym-mainnet-archivenode":          "Dymension Mainnet Archivenode",
	"dym-mainnet-fullnode":             "Dymension Mainnet Fullnode",
	"dym-mainnet-unchained":            "Dymension Mainnet Unchained",
	"dym-testnet-archivenode":          "Dymension Testnet Archivenode",
	"dym-testnet-fullnode":             "Dymension Testnet Fullnode",
	"erowan-mainnet-archivenode":       "Sifchain Mainnet Archivenode",
	"erowan-mainnet-fullnode":          "Sifchain Mainnet Fullnode",
	"etc-mainnet-blockbook":            "Ethereum Classic Mainnet Blockbook",
	"etc-mainnet-unchained":            "Ethereum Classic Mainnet Unchained",
	"eth-holesky-testnet-blockbook":    "Ethereum Holesky Testnet Blockbook",
	"eth-holesky-testnet-fullnode":     "Ethereum Holesky Testnet Fullnode",
	"eth-holesky-testnet-unchained":    "Ethereum Holesky Testnet Unchained",
	"eth-mainnet-blockbook":            "Ethereum Mainnet Blockbook",
	"eth-sepolia-testnet-blockbook":    "Ethereum Sepolia Testnet Blockbook",
	"eth-sepolia-testnet-fullnode":     "Ethereum Sepolia Testnet Fullnode",
	"eth-sepolia-testnet-unchained":    "Ethereum Sepolia Testnet Unchained",
	"evmos-mainnet-archivenode":        "Evmos Mainnet Archivenode",
	"evmos-mainnet-fullnode":           "Evmos Mainnet Fullnode",
	"evmos-testnet-archivenode":        "Evmos Testnet Archivenode",
	"evmos-testnet-fullnode":           "Evmos Testnet Fullnode",
	"fil-mainnet-fullnode":             "Filecoin Mainnet Fullnode",
	"fil-mainnet-unchained":            "Filecoin Mainnet Unchained",
	"fil-testnet-fullnode":             "Filecoin Testnet Fullnode",
	"flare-mainnet-archivenode":        "Flare Mainnet Archivenode",
	"flare-mainnet-fullnode":           "Flare Mainnet Fullnode",
	"flare-mainnet-unchained":          "Flare Mainnet Unchained",
	"flare-testnet-archivenode":        "Flare Testnet Archivenode",
	"flare-testnet-fullnode":           "Flare Testnet Fullnode",
	"flo-mainnet-fullnode":             "Florincoin Mainnet Fullnode",
	"flow-mainnet-fullnode":            "Flow Mainnet Fullnode",
	"flow-mainnet-unchained":           "Flow Mainnet Unchained",
	"flow-testnet-fullnode":            "Flow Testnet Fullnode",
	"frx-mainnet-archivenode":          "Fraxtal Mainnet Archivenode",
	"frx-mainnet-fullnode":             "Fraxtal Mainnet Fullnode",
	"frx-mainnet-unchained":            "Fraxtal Mainnet Unchained",
	"frx-testnet-archivenode":          "Fraxtal Testnet Archivenode",
	"frx-testnet-fullnode":             "Fraxtal Testnet Fullnode",
	"ftc-mainnet-fullnode":             "Feathercoin Mainnet Fullnode",
	"ftm-mainnet-archivenode":          "Fantom Mainnet Archivenode",
	"ftm-mainnet-fullnode":             "Fantom Mainnet Fullnode",
	"ftm-mainnet-unchained":            "Fantom Mainnet Unchained",
	"ftm-testnet-archivenode":          "Fantom Testnet Archivenode",
	"ftm-testnet-fullnode":             "Fantom Testnet Fullnode",
	"fuse-mainnet-archivenode":         "Fuse Mainnet Archivenode",
	"fuse-mainnet-fullnode":            "Fuse Mainnet Fullnode",
	"fuse-testnet-archivenode":         "Fuse Testnet Archivenode",
	"fuse-testnet-fullnode":            "Fuse Testnet Fullnode",
	"gaia-mainnet-archivenode":         "Cosmos Hub (Gaia) Mainnet Archivenode",
	"gaia-mainnet-fullnode":            "Cosmos Hub (Gaia) Mainnet Fullnode",
	"gaia-mainnet-fullnode-grpc":       "Cosmos Hub (Gaia) Mainnet Fullnode Grpc",
	"gaia-testnet-archivenode":         "Cosmos Hub (Gaia) Testnet Archivenode",
	"gaia-testnet-fullnode":            "Cosmos Hub (Gaia) Testnet Fullnode",
	"glmr-mainnet-archivenode":         "Moonbeam Mainnet Archivenode",
	"glmr-mainnet-fullnode":            "Moonbeam Mainnet Fullnode",
	"glmr-mainnet-unchained":           "Moonbeam Mainnet Unchained",
	"glmr-testnet-archivenode":         "Moonbeam Testnet Archivenode",
	"glmr-testnet-fullnode":            "Moonbeam Testnet Fullnode",
	"grs-mainnet-fullnode":             "Groestlcoin Mainnet Fullnode",
	"hbar-mainnet-fullnode":            "Hedera Mainnet Fullnode",
	"hbar-mainnet-unchained":           "Hedera Mainnet Unchained",
	"hbar-testnet-fullnode":            "Hedera Testnet Fullnode",
	"hopr-mainnet-fullnode":            "HOPR Mainnet Fullnode",
	"hopr-testnet-fullnode":            "HOPR Testnet Fullnode",
	"imx-mainnet-archivenode":          "Immutable Mainnet Archivenode",
	"imx-mainnet-fullnode":             "Immutable Mainnet Fullnode",
	"imx-mainnet-unchained":            "Immutable Mainnet Unchained",
	"imx-testnet-archivenode":          "Immutable Testnet Archivenode",
	"imx-testnet-fullnode":             "Immutable Testnet Fullnode",
	"initia-mainnet-archivenode":       "Initia Mainnet Archivenode",
	"initia-mainnet-fullnode":          "Initia Mainnet Fullnode",
	"inj-mainnet-archivenode":          "Injective Protocol Mainnet Archivenode",
	"inj-mainnet-fullnode":             "Injective Protocol Mainnet Fullnode",
	"inj-mainnet-unchained":            "Injective Protocol Mainnet Unchained",
	"inj-testnet-archivenode":          "Injective Protocol Testnet Archivenode",
	"inj-testnet-fullnode":             "Injective Protocol Testnet Fullnode",
	"iota-mainnet-fullnode":            "IOTA Mainnet Fullnode",
	"iotx-mainnet-fullnode":            "IoTex Mainnet Fullnode",
	"ixo-mainnet-archivenode":          "IXO Mainnet Archivenode",
	"ixo-mainnet-fullnode":             "IXO Mainnet Fullnode",
	"jackal-mainnet-archivenode":       "Jackal Mainnet Archivenode",
	"jackal-mainnet-fullnode":          "Jackal Mainnet Fullnode",
	"juno-mainnet-archivenode":         "Juno Mainnet Archivenode",
	"juno-mainnet-fullnode":            "Juno Mainnet Fullnode",
	"juno-mainnet-unchained":           "Juno Mainnet Unchained",
	"juno-testnet-archivenode":         "Juno Testnet Archivenode",
	"juno-testnet-fullnode":            "Juno Testnet Fullnode",
	"kava-mainnet-archivenode":         "Kava EVM Mainnet Archivenode",
	"kava-mainnet-fullnode":            "Kava EVM Mainnet Fullnode",
	"kava-testnet-archivenode":         "Kava EVM Testnet Archivenode",
	"kava-testnet-fullnode":            "Kava EVM Testnet Fullnode",
	"klay-mainnet-archivenode":         "Klaytn Mainnet Archivenode",
	"klay-mainnet-fullnode":            "Klaytn Mainnet Fullnode",
	"klay-mainnet-unchained":           "Klaytn Mainnet Unchained",
	"klay-testnet-archivenode":         "Klaytn Testnet Archivenode",
	"klay-testnet-fullnode":            "Klaytn Testnet Fullnode",
	"koii-mainnet-fullnode":            "Koii Mainnet Fullnode",
	"lbtc-mainnet-fullnode":            "Liquid Mainnet Fullnode",
	"linea-mainnet-archivenode":        "Linea Mainnet Archivenode",
	"linea-mainnet-fullnode":           "Linea Mainnet Fullnode",
	"linea-mainnet-unchained":          "Linea Mainnet Unchained",
	"linea-testnet-archivenode":        "Linea Testnet Archivenode",
	"linea-testnet-fullnode":           "Linea Testnet Fullnode",
	"ln-mainnet-fullnode":              "Lightning Network Mainnet Fullnode",
	"manta-mainnet-fullnode":           "Manta Mainnet Fullnode",
	"manta-mainnet-unchained":          "Manta Mainnet Unchained",
	"mantle-mainnet-archivenode":       "Mantle Mainnet Archivenode",
	"mantle-mainnet-fullnode":          "Mantle Mainnet Fullnode",
	"mantle-mainnet-unchained":         "Mantle Mainnet Unchained",
	"mantra-mainnet-archivenode":       "Mantra Mainnet Archivenode",
	"mantra-mainnet-fullnode":          "Mantra Mainnet Fullnode",
	"maya-mainnet-archivenode":         "Maya Protocol Mainnet Archivenode",
	"maya-mainnet-fullnode":            "Maya Protocol Mainnet Fullnode",
	"mina-mainnet-fullnode":            "Mina Mainnet Fullnode",
	"mina-mainnet-unchained":           "Mina Mainnet Unchained",
	"mona-mainnet-fullnode":            "MonaCoin Mainnet Fullnode",
	"movr-mainnet-archivenode":         "Moonriver Mainnet Archivenode",
	"movr-mainnet-fullnode":            "Moonriver Mainnet Fullnode",
	"movr-testnet-archivenode":         "Moonriver Testnet Archivenode",
	"movr-testnet-fullnode":            "Moonriver Testnet Fullnode",
	"namada-mainnet-archivenode":       "Namada Mainnet Archivenode",
	"namada-mainnet-fullnode":          "Namada Mainnet Fullnode",
	"near-mainnet-fullnode":            "NEAR Mainnet Fullnode",
	"near-mainnet-unchained":           "NEAR Mainnet Unchained",
	"near-testnet-fullnode":            "NEAR Testnet Fullnode",
	"neutron-mainnet-archivenode":      "Neutron Mainnet Archivenode",
	"neutron-mainnet-fullnode":         "Neutron Mainnet Fullnode",
	"neutron-mainnet-unchained":        "Neutron Mainnet Unchained",
	"ngm-mainnet-archivenode":          "e-Money Mainnet Archivenode",
	"ngm-mainnet-fullnode":             "e-Money Mainnet Fullnode",
	"ngm-testnet-archivenode":          "e-Money Testnet Archivenode",
	"ngm-testnet-fullnode":             "e-Money Testnet Fullnode",
	"nibiru-mainnet-archivenode":       "Nibiru Network Mainnet Archivenode",
	"nibiru-mainnet-fullnode":          "Nibiru Network Mainnet Fullnode",
	"nlg-mainnet-fullnode":             "Gulden Mainnet Fullnode",
	"nmc-mainnet-fullnode":             "Namecoin Mainnet Fullnode",
	"nomic-mainnet-archivenode":        "Nomic Mainnet Archivenode",
	"nomic-mainnet-fullnode":           "Nomic Mainnet Fullnode",
	"one-mainnet-fullnode":             "Harmony Mainnet Fullnode",
	"one-testnet-fullnode":             "Harmony Testnet Fullnode",
	"optimism-mainnet-archivenode":     "Optimism Mainnet Archivenode",
	"osmosis-mainnet-archivenode":      "Osmosis Mainnet Archivenode",
	"paloma-mainnet-archivenode":       "Paloma Mainnet Archivenode",
	"paloma-mainnet-fullnode":          "Paloma Mainnet Fullnode",
	"part-mainnet-fullnode":            "Particl Mainnet Fullnode",
	"penumbra-mainnet-archivenode":     "Penumbra Mainnet Archivenode",
	"penumbra-mainnet-fullnode":        "Penumbra Mainnet Fullnode",
	"polkadot-testnet-archivenode":     "Polkadot Testnet Archivenode",
	"polkadot-testnet-fullnode":        "Polkadot Testnet Fullnode",
	"polkadot-testnet-lightnode":       "Polkadot Testnet Lightnode",
	"polygon-Mumbai-testnet-fullnode":  "Polygon Mumbai Testnet Fullnode",
	"polygon-Mumbai-testnet-unchained": "Polygon Mumbai Testnet Unchained",
	"polygon-mainnet-unchained":        "Polygon Mainnet Unchained",
	"ppc-mainnet-fullnode":             "Peercoin Mainnet Fullnode",
	"pyth-mainnet-fullnode":            "Pyth Network Mainnet Fullnode",
	"pyth-testnet-fullnode":            "Pyth Network Testnet Fullnode",
	"qtum-mainnet-blockbook":           "Qtum Mainnet Blockbook",
	"qtum-mainnet-fullnode":            "Qtum Mainnet Fullnode",
	"rdd-mainnet-fullnode":             "Reddcoin Mainnet Fullnode",
	"router-mainnet-archivenode":       "Router Network Mainnet Archivenode",
	"router-mainnet-fullnode":          "Router Network Mainnet Fullnode",
	"rvn-mainnet-blockbook":            "Ravencoin Mainnet Blockbook",
	"rvn-mainnet-fullnode":             "Ravencoin Mainnet Fullnode",
	"scroll-mainnet-archivenode":       "Scroll Mainnet Archivenode",
	"scroll-mainnet-fullnode":          "Scroll Mainnet Fullnode",
	"scroll-mainnet-unchained":         "Scroll Mainnet Unchained",
	"scroll-testnet-archivenode":       "Scroll Testnet Archivenode",
	"scroll-testnet-fullnode":          "Scroll Testnet Fullnode",
	"scrt-mainnet-archivenode":         "Secret Network Mainnet Archivenode",
	"scrt-mainnet-fullnode":            "Secret Network Mainnet Fullnode",
	"seda-mainnet-fullnode":            "Seda Mainnet Fullnode",
	"sei-mainnet-archivenode":          "Sei Mainnet Archivenode",
	"sei-mainnet-fullnode":             "Sei Mainnet Fullnode",
	"sei-mainnet-unchained":            "Sei Mainnet Unchained",
	"sei-testnet-archivenode":          "Sei Testnet Archivenode",
	"sei-testnet-fullnode":             "Sei Testnet Fullnode",
	"selfchain-mainnet-archivenode":    "Selfchain Mainnet Archivenode",
	"selfchain-mainnet-fullnode":       "Selfchain Mainnet Fullnode",
	"shardeum-mainnet-archivenode":     "Shardeum Mainnet Archivenode",
	"shardeum-mainnet-fullnode":        "Shardeum Mainnet Fullnode",
	"shardeum-mainnet-unchained":       "Shardeum Mainnet Unchained",
	"shardeum-testnet-archivenode":     "Shardeum Testnet Archivenode",
	"shardeum-testnet-fullnode":        "Shardeum Testnet Fullnode",
	"smart-mainnet-fullnode":           "SmartCash Mainnet Fullnode",
	"sol-mainnet-unchained":            "Solana Mainnet Unchained",
	"sol-testnet-fullnode":             "Solana Testnet Fullnode",
	"somnia-mainnet-archivenode":       "Somnia Mainnet Archivenode",
	"somnia-mainnet-fullnode":          "Somnia Mainnet Fullnode",
	"starknet-mainnet-archivenode":     "Starknet Mainnet Archivenode",
	"starknet-mainnet-fullnode":        "Starknet Mainnet Fullnode",
	"starknet-testnet-archivenode":     "Starknet Testnet Archivenode",
	"starknet-testnet-fullnode":        "Starknet Testnet Fullnode",
	"stride-mainnet-archivenode":       "Stride Mainnet Archivenode",
	"stride-mainnet-fullnode":          "Stride Mainnet Fullnode",
	"sui-mainnet-fullnode":             "SUI Mainnet Fullnode",
	"sui-testnet-fullnode":             "SUI Testnet Fullnode",
	"supra-mainnet-archivenode":        "SUPRA Mainnet Archivenode",
	"supra-mainnet-fullnode":           "SUPRA Mainnet Fullnode",
	"sys-mainnet-fullnode":             "Syscoin Mainnet Fullnode",
	"taiko-mainnet-archivenode":        "Taiko Mainnet Archivenode",
	"taiko-mainnet-fullnode":           "Taiko Mainnet Fullnode",
	"taiko-mainnet-unchained":          "Taiko Mainnet Unchained",
	"taiko-testnet-archivenode":        "Taiko Testnet Archivenode",
	"taiko-testnet-fullnode":           "Taiko Testnet Fullnode",
	"thorchain-mainnet-archivenode":    "Thorchain Mainnet Archivenode",
	"tia-mainnet-archivenode":          "Celestia Mainnet Archivenode",
	"tia-mainnet-fullnode":             "Celestia Mainnet Fullnode",
	"tia-mainnet-unchained":            "Celestia Mainnet Unchained",
	"tia-testnet-archivenode":          "Celestia Testnet Archivenode",
	"tia-testnet-fullnode":             "Celestia Testnet Fullnode",
	"ton-mainnet-fullnode":             "TON Mainnet Fullnode",
	"ton-testnet-fullnode":             "TON Testnet Fullnode",
	"trx-mainnet-archivenode":          "Tron Mainnet Archivenode",
	"trx-mainnet-fullnode":             "Tron Mainnet Fullnode",
	"trx-mainnet-unchained":            "Tron Mainnet Unchained",
	"trx-testnet-archivenode":          "Tron Testnet Archivenode",
	"trx-testnet-fullnode":             "Tron Testnet Fullnode",
	"union-mainnet-archivenode":        "Union Mainnet Archivenode",
	"union-mainnet-fullnode":           "Union Mainnet Fullnode",
	"via-mainnet-fullnode":             "Viacoin Mainnet Fullnode",
	"vtc-mainnet-fullnode":             "Vertcoin Mainnet Fullnode",
	"xdai-mainnet-archivenode":         "Gnosis Chain Mainnet Archivenode",
	"xdai-mainnet-fullnode":            "Gnosis Chain Mainnet Fullnode",
	"xdai-mainnet-unchained":           "Gnosis Chain Mainnet Unchained",
	"xdai-testnet-archivenode":         "Gnosis Chain Testnet Archivenode",
	"xdai-testnet-fullnode":            "Gnosis Chain Testnet Fullnode",
	"xec-mainnet-fullnode":             "eCash Mainnet Fullnode",
	"xlm-mainnet-fullnode":             "Stellar Mainnet Fullnode",
	"xlm-testnet-fullnode":             "Stellar Testnet Fullnode",
	"xprt-mainnet-archivenode":         "Persistence Mainnet Archivenode",
	"xprt-mainnet-fullnode":            "Persistence Mainnet Fullnode",
	"zec-mainnet-blockbook":            "Zcash Mainnet Blockbook",
	"zec-mainnet-fullnode":             "Zcash Mainnet Fullnode",
	"zircuit-mainnet-archivenode":      "Zircuit Mainnet Archivenode",
	"zircuit-mainnet-fullnode":         "Zircuit Mainnet Fullnode",
	"zircuit-mainnet-unchained":        "Zircuit Mainnet Unchained",
	"zircuit-testnet-archivenode":      "Zircuit Testnet Archivenode",
	"zircuit-testnet-fullnode":         "Zircuit Testnet Fullnode",
	"zkfair-mainnet-archivenode":       "zkFair Mainnet Archivenode",
	"zkfair-mainnet-fullnode":          "zkFair Mainnet Fullnode",
	"zkfair-mainnet-unchained":         "zkFair Mainnet Unchained",
	"zkfair-testnet-archivenode":       "zkFair Testnet Archivenode",
	"zkfair-testnet-fullnode":          "zkFair Testnet Fullnode",
	"zksync-mainnet-archivenode":       "ZkSync Mainnet Archivenode",
	"zksync-mainnet-fullnode":          "ZkSync Mainnet Fullnode",
	"zksync-mainnet-unchained":         "ZkSync Mainnet Unchained",
	"zksync-testnet-archivenode":       "ZkSync Testnet Archivenode",
	"zksync-testnet-fullnode":          "ZkSync Testnet Fullnode",
}

func (c Service) String() string {
	if r, ok := ServiceReverseLookup[c]; ok {
		return r
	}
	return "unknown"
}

// NewService create a new service
func NewService(serviceId string) (Service, error) {
	service := ServiceLookup[strings.ToLower(serviceId)]
	if service == 0 {
		return Service(service), fmt.Errorf("service not found (%s)", serviceId)
	}
	return Service(service), nil
}

// Equals compare two services to see whether they represent the same service
func (c Service) Equals(c2 Service) bool {
	return strings.EqualFold(c.String(), c2.String())
}

// IsEmpty is to determinate whether the service is empty
func (c Service) IsEmpty() bool {
	return strings.TrimSpace(c.String()) == ""
}
