name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: release-cross
        run: make release-cross
        env:
          RELEASE: true
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        
      - name: release
        run: make release
        env:
          RELEASE: true
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}