name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
    release-check:
        name: Check release
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version-file: go.mod
        
        - name: Compile Protobuf
          run: make proto-gen

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: GoReleaser Cross
          run: make release-dry-run-cross
          env:
            RELEASE: false
            GITHUB_TOKEN: ""
        - name: GoReleaser
          run: make release-dry-run
          env:
            RELEASE: false
            GITHUB_TOKEN: ""